title: Afillyate Photography
description: Event and portrait photography
url: "https://badgeronabike.github.io"
baseurl: "/afillyateGHP"

collections:
  events:
    output: true
    permalink: /events/:name/