title: Afillyate Photography
description: Event and portrait photography
url: "https://badgeronabike.github.io"
baseurl: "/afillyate_GHP"

collections:
  events:
    output: true
    permalink: /events/:name/